window.demoVehicles = [
  {
    id: 1,
    type: "Car",
    brand: "Hyundai i20",
    location: "Delhi",
    price: 1200,
    availableFrom: "2025-07-01",
    availableTo: "2025-07-10",
    images: ["images/hyundai.jpg"],
    listerEmail: "host1@example.com",
    listerName: "Ankit Sharma"
  },
  {
    id: 2,
    type: "Bike",
    brand: "Honda Activa",
    location: "Mumbai",
    price: 400,
    availableFrom: "2025-07-05",
    availableTo: "2025-07-15",
    images: ["images/honda.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Priya Mehra"
  },
  {
    id: 3,
    type: "Car",
    brand: "Scorpio",
    location: "Hydrabad",
    price: 500,
    availableFrom: "2025-07-10",
    availableTo: "2025-07-15",
    images: ["images/scorpio.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Abhishek Verma"
  },
  {
    id: 4,
    type: "Bike",
    brand: "Royal Enfield",
    location: "Chandigarh",
    price: 700,
    availableFrom: "2025-07-25",
    availableTo: "2025-07-28",
    images: ["images/royal.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Rohit Saw"
  },
  {
    id: 5,
    type: "Scooter",
    brand: "Honda Activa",
    location: "Pune",
    price: 300,
    availableFrom: "2025-07-20",
    availableTo: "2025-07-25",
    images: ["images/hondaActiva2.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Jacky"
  },
  {
    id: 6,
    type: "Car",
    brand: "Tata Motors",
    location: "Hydrabad",
    price: 1200,
    availableFrom: "2025-07-01",
    availableTo: "2025-07-10",
    images: ["images/tata.jpg"],
    listerEmail: "host1@example.com",
    listerName: "Ankit Sharma"
  },
  {
    id: 7,
    type: "Scooter",
    brand: "TVS",
    location: "Mumbai",
    price: 400,
    availableFrom: "2025-07-05",
    availableTo: "2025-07-15",
    images: ["images/tvs.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Priya Mehra"
  },
  {
    id: 8,
    type: "Car",
    brand: "Jeep Cherokee",
    location: "Hariyana",
    price: 500,
    availableFrom: "2025-07-10",
    availableTo: "2025-07-15",
    images: ["images/JeepCherokee.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Abhishek Verma"
  },
  {
    id: 9,
    type: "Bike",
    brand: "KTM-Duke Kawasaki",
    location: "Chandigarh",
    price: 700,
    availableFrom: "2025-07-25",
    availableTo: "2025-07-28",
    images: ["images/ktm.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Rohit Saw"
  },
  {
    id: 10,
    type: "Car",
    brand: "Honda City",
    location: "Pune",
    price: 300,
    availableFrom: "2025-07-20",
    availableTo: "2025-07-25",
    images: ["images/hondaCity2.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Jacky"
  },
  {
    id: 11,
    type: "Car",
    brand: "Hyndai i20",
    location: "Hydrabad",
    price: 1200,
    availableFrom: "2025-07-01",
    availableTo: "2025-07-10",
    images: ["images/hyndai2.jpg"],
    listerEmail: "host1@example.com",
    listerName: "Ankit Sharma"
  },
  {
    id: 12,
    type: "Car",
    brand: "Honda City",
    location: "Mumbai",
    price: 400,
    availableFrom: "2025-07-05",
    availableTo: "2025-07-15",
    images: ["images/hondaCity.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Priya Mehra"
  },
  {
    id: 13,
    type: "Car",
    brand: "Scorpio",
    location: "Hydrabad",
    price: 500,
    availableFrom: "2025-07-10",
    availableTo: "2025-07-15",
    images: ["images/scorpio2.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Abhishek Verma"
  },
  {
    id: 14,
    type: "Bike",
    brand: "Royal Enfield",
    location: "Chandigarh",
    price: 700,
    availableFrom: "2025-07-25",
    availableTo: "2025-07-28",
    images: ["images/royal3.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Rohit Saw"
  },
  {
    id: 15,
    type: "Scooter",
    brand: "Honda Activa",
    location: "Pune",
    price: 300,
    availableFrom: "2025-07-20",
    availableTo: "2025-07-25",
    images: ["images/hondaActiva.jpg"],
    listerEmail: "host2@example.com",
    listerName: "Jacky"
  },
];